name: task_todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  theme_tailor_annotation: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: 2.4.13
  flutter_gen_runner: ^5.8.0
  theme_tailor: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/card_night.png
    - assets/images/card_sunset.png
    - assets/images/card_sunrise.png
